export type {
    PaletteShades,
    PaletteShade,
    PaletteRef,
    VariantStateSlots,
    VariantStates,
    InteractiveScheme,
    ButtonDesign,
    FieldContainerVariant,
    TabConfig,
    ConfigState,
    TypographyConfig,
    HeadingLevelConfig,
    TextSizeConfig,
    ParagraphSizeConfig,
    TypographyResponsiveTier,
    ParagraphResponsiveTier,
} from '@reformjs/reactive/config/types';
