export type {
    PaletteShades,
    InteractiveVariant,
    InteractiveScheme,
    ButtonVariant,
    FieldContainerVariant,
    TabConfig,
    ConfigState,
    TypographyConfig,
    HeadingLevelConfig,
    TextSizeConfig,
    ParagraphSizeConfig,
    TypographyResponsiveTier,
    ParagraphResponsiveTier,
} from '@reformjs/reactive/config/types';
