module.exports = {
    extends: [
        'eslint:recommended',
        'airbnb',
        'airbnb-typescript/base',
        'prettier',
    ],
    ignorePatterns: ['.eslintrc.*js', 'rollup.config.*js', 'jest.config.*js'],
    parserOptions: {
        parser: '@typescript-eslint/parser',
        ecmaVersion: 'latest',
        project: true,
    },
    plugins: ['jest', 'import'],
    env: {
        'jest/globals': true,
        browser: true,
    },
    rules: {
        'no-tabs': 0,
        indent: 0,
        'import/extensions': 0,
        'react/jsx-filename-extension': [
            1,
            { extensions: ['.jsx', '.tsx'] },
        ],
        '@typescript-eslint/indent': 0,
        'no-dupe-keys': 'error',
        'react/jsx-props-no-spreading': 0,
        'react/require-default-props': 0,
        'react/prop-types': 0,
        'react/static-property-placement': 0,
        'react/no-unused-class-component-methods': 0,
        'react/no-unused-prop-types': 0,
        'no-underscore-dangle': 0,
        'import/no-cycle': 0,
        'no-plusplus': 0,
        'class-methods-use-this': 0,
        '@typescript-eslint/no-unused-vars': ['warn', {
            argsIgnorePattern: '^_',
            varsIgnorePattern: '^_',
        }],
        'no-console': 'warn',
        'no-alert': 'warn',
        'max-classes-per-file': 0,
        'no-param-reassign': ['error', { props: false }],
        'import/prefer-default-export': 0,
        'import/no-anonymous-default-export': 0,
        'max-len': 0,
        'no-await-in-loop': 0,
    },
};
